Multiple Updates - see below
RemoveMyProcrastination/rmp pull request #15
Opened 2016-11-23 23:09 UTC by ByronBecker

Added Info on the list of accessible api urls, the database structure, added the getgoal api call, deleted unneccessary print statements, and added some comments to improve readability

2016-11-23 23:58 UTC, Anonymous-Stranger requested changes
Overall, awesome job. Documentation is amazing. Just a few things that are a little nonstandard, so we should discuss whether to keep/change them.

2016-11-23 23:58 UTC, Anonymous-Stranger commented on newUser.py
> +3. '/get/<string:name>/' is a get request that returns all of the information in the database corresponding to a specific name user including goals, _id, _rev, etc.
It might be dangerous to use usernames here. Perhaps a user id would be better?

2016-11-23 23:58 UTC, Anonymous-Stranger commented on newUser.py
> +6. '/app/<string:name>/<string:app>' is open to both PUT and DELETE requests
Same risk here (names instead of ids). Maybe give apps ids?

2016-11-23 23:58 UTC, Anonymous-Stranger commented on newUser.py
> +3. '/get/<string:name>/' is a get request that returns all of the information in the database corresponding to a specific name user including goals, _id, _rev, etc.
Usually, all the user actions would be grouped under /user/, so
GET /user/\<string:id\>/ would get a user,
POST /user/ would create a user,
PUT /user/\<string:id\>/ would update a user,
DELETE /user/\<string:id\>/ would delete a user.

2016-11-23 23:58 UTC, Anonymous-Stranger commented on newUser.py
> +7. '/getgoal/<string:name>/' is a get request that retrieves the Daily and Weekly Goals from the server
Similarly, we would use /goals/\<string:userid\> or /user/\<string:userid\>/goals/.

2016-11-24 00:04 UTC, ByronBecker commented on newUser.py
> +3. '/get/<string:name>/' is a get request that returns all of the information in the database corresponding to a specific name user including goals, _id, _rev, etc.
The newusers are created with the doc _id having the name of the newuser, which is then how we access the documents. If we then do it with a user id (which I agree is more secure) say 0075, then we need the client to remember this user id so that it can be referenced going forward. I can easily change this once we get into the integration more.

2016-11-24 00:04 UTC, ByronBecker commented on newUser.py
> +3. '/get/<string:name>/' is a get request that returns all of the information in the database corresponding to a specific name user including goals, _id, _rev, etc.
Sounds good, I'll edit this

2016-11-24 00:08 UTC, ByronBecker commented on newUser.py
> +6. '/app/<string:name>/<string:app>' is open to both PUT and DELETE requests
Now that I think about it more, a better solution would be to restrict access to the apis based upon the username that is currently logged in. So once logged in, they can only access a specific <string:name> route.

2016-11-24 01:28 UTC, ByronBecker commented
I thought a bit more about the having the first element be unanimous in them all being /user/variable/variable, and there might be some confusion/less options  

I’m thinking about it sort of like Huffman prefix coding (from algorithms). If we keep the first part of the path the same across all the url paths, we have less options for paths. We can discuss this further or I can change it if you still disagree. Going to push it through for now.

2016-11-24 01:29 UTC, merged